### ISSUE TITLE
rubidium incompability

### ISSUE THREAD

**Issue by Bonnie22556** [xTracr/RealCamera#101]
ummm...

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2024-09-05 17:03:10
Description: Rendering entity in world

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mods: 
	Rubidium (rubidium), Version: 0.7.1
		at TRANSFORMER/rubidium@0.7.1/net.caffeinemc.mods.sodium.api.vertex.buffer.VertexBufferWriter.createUnsupportedVertexConsumerThrowable(VertexBufferWriter.java:46)

	Real Camera (realcamera), Version: 0.6.1-beta
		Issue tracker URL: https://github.com/xTracr/RealCamera/issues
		at TRANSFORMER/realcamera@0.6.1-beta/com.xtracr.realcamera.RealCameraCore.updateModel(RealCameraCore.java:90)

**Comment by Shopper7** [comment]
If you haven't figured this out yet, run Embeddium in place of Rubidium. Embeddium is 100% compatible.

**Comment by H31M5** [comment]
The new version is fully compatible/supported
